export const GET_ALL_CLIENTS__START = 'GET_ALL_CLIENTS__START';
export const GET_ALL_CLIENTS__SUCCESS = 'GET_ALL_CLIENTS__SUCCESS';
export const GET_ALL_CLIENTS__FAILURE = 'GET_ALL_CLIENTS__FAILURE';

export const CREATE_CLIENT__START = 'CREATE_CLIENT__START';
export const CREATE_CLIENT__SUCCESS = 'CREATE_CLIENT__SUCCESS';
export const CREATE_CLIENT__FAILURE = 'CREATE_CLIENT__FAILURE';
