export const GET_ALL_APPOINTMENTS__START = 'GET_ALL_APPOINTMENTS__START';
export const GET_ALL_APPOINTMENTS__SUCCESS = 'GET_ALL_APPOINTMENTS__SUCCESS';
export const GET_ALL_APPOINTMENTS__FAILURE = 'GET_ALL_APPOINTMENTS__FAILURE';

export const CREATE_APPOINTMENT__START = 'CREATE_APPOINTMENT__START';
export const CREATE_APPOINTMENT__SUCCESS = 'CREATE_APPOINTMENT__SUCCESS';
export const CREATE_APPOINTMENT__FAILURE = 'CREATE_APPOINTMENT__FAILURE';
