export const GET_ALL_STAFFMEMBERS__START = 'GET_ALL_STAFFMEMBERS__START';
export const GET_ALL_STAFFMEMBERS__SUCCESS = 'GET_ALL_STAFFMEMBERS__SUCCESS';
export const GET_ALL_STAFFMEMBERS__FAILURE = 'GET_ALL_STAFFMEMBERS__FAILURE';

export const CREATE_STAFFMEMBER__START = 'CREATE_STAFFMEMBER__START';
export const CREATE_STAFFMEMBER__SUCCESS = 'CREATE_STAFFMEMBER__SUCCESS';
export const CREATE_STAFFMEMBER__FAILURE = 'CREATE_STAFFMEMBER__FAILURE';
